# Generated by Django 5.2.16 on 2026-07-09 13:55

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_users',
                'indexes': [models.Index(fields=['is_active'], name='auth_users_is_active_idx'), models.Index(fields=['deleted_at'], name='auth_users_deleted_at_idx'), models.Index(fields=['created_at'], name='auth_users_created_at_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='auth_users_email_lower_unique'), models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', False), _connector='OR'), name='auth_users_deleted_at_requires_inactive')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_hash', models.CharField(max_length=255, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='auth_service.user')),
            ],
            options={
                'db_table': 'auth_sessions',
                'indexes': [models.Index(fields=['user'], name='auth_sessions_user_idx'), models.Index(fields=['user', 'revoked_at'], name='auth_sessions_user_revoked_idx'), models.Index(fields=['expires_at'], name='auth_sessions_expires_at_idx'), models.Index(fields=['created_at'], name='auth_sessions_created_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='auth_sessions_expires_after_created')],
            },
        ),
    ]
