# Generated by Django 5.2.16 on 2026-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsession',
            name='refresh_token_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='authsession',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('created_at')), _connector='OR'), name='auth_sessions_revoke_time'),
        ),
    ]
