# Generated by Django 5.2.16 on 2026-07-10 15:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must start with a lowercase Latin letter and contain only lowercase Latin letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'access_actions',
                'indexes': [models.Index(fields=['is_active'], name='access_actions_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Code must start with a lowercase Latin letter and contain only lowercase Latin letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('has_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'access_resources',
                'indexes': [models.Index(fields=['is_active'], name='access_res_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must start with a lowercase Latin letter and contain only lowercase Latin letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'access_roles',
                'indexes': [models.Index(fields=['is_active'], name='access_roles_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('none', 'No access'), ('own', 'Own objects'), ('all', 'All objects')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_policies', to='access_service.accessaction')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_policies', to='access_service.accessresource')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_policies', to='access_service.role')),
            ],
            options={
                'db_table': 'access_policies',
                'indexes': [models.Index(fields=['role', 'resource', 'action'], name='access_policy_lookup_idx'), models.Index(fields=['resource', 'action', 'is_active'], name='access_policy_res_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'resource', 'action'), name='access_policy_role_res_act_uniq'), models.CheckConstraint(condition=models.Q(('scope__in', ['none', 'own', 'all'])), name='access_policy_scope_valid')],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_role_assignments', to='auth_service.user')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_role_assignments', to='auth_service.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='access_service.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='auth_service.user')),
            ],
            options={
                'db_table': 'access_user_role_assignments',
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='access_ur_user_revoked_idx'), models.Index(fields=['role', 'revoked_at'], name='access_ur_role_revoked_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role'), name='access_user_role_active_uniq'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('created_at')), _connector='OR'), name='access_user_role_revoke_time')],
            },
        ),
    ]
